// Writes WALKTHROUGH.md from the same manifest and sources the app renders,
// for reading without running anything: `pnpm walkthrough`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import { flow } from "../flow/manifest.mjs";
import { readSource } from "../lib/source.mjs";

const root = resolve(dirname(new URL(import.meta.url).pathname), "..");
const recipe = JSON.parse(
  readFileSync(join(root, "recipe/SOURCE.json"), "utf8"),
);
const fence = (language) => (language === "markdown" ? "md" : language);

const out = [
  `# ${flow.title}`,
  "",
  "<!-- Generated by `pnpm walkthrough` from flow/manifest.mjs. Edit the manifest, not this file. -->",
  "",
  flow.intro,
  "",
  `Recipe code is from [recipe-travel-agent@${recipe.commit.slice(0, 7)}](${recipe.repository}/tree/${recipe.commit}). Platform steps show the contract on the wire, not the code.`,
  "",
];

flow.steps.forEach((step, index) => {
  out.push(
    `## ${index + 1}. ${step.title}`,
    "",
    `*${step.actor}*`,
    "",
    step.body,
    "",
  );
  for (const source of step.sources) {
    const { code, language, origin } = readSource(root, source);
    out.push(
      `**${source.label ?? source.path}** · \`${origin}\``,
      "",
      "```" + fence(language),
      code,
      "```",
      "",
    );
  }
});

writeFileSync(join(root, "WALKTHROUGH.md"), out.join("\n"));
console.log(`wrote WALKTHROUGH.md (${flow.steps.length} steps)`);
